-- Table to store root chapters
CREATE TABLE chapters (
    chapter_number SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table to store localized chapter names
CREATE TABLE chapter_descriptions (
    id SERIAL PRIMARY KEY,
    chapter_number INT REFERENCES chapters(chapter_number) ON DELETE CASCADE,
    language_code VARCHAR(2) NOT NULL,
    chapter_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(chapter_number, language_code)
);


-- Indexes for common queries
CREATE INDEX idx_chapter_descriptions_language_code ON chapter_descriptions(language_code);

-- Indexes for common queries
CREATE INDEX idx_chapter_descriptions_language_code ON chapter_descriptions(language_code);

-- Trigger to update the updated_at timestamp automatically
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_chapters_modtime
BEFORE UPDATE ON chapters
FOR EACH ROW EXECUTE FUNCTION update_modified_column();

CREATE TRIGGER update_chapter_descriptions_modtime
BEFORE UPDATE ON chapter_descriptions
FOR EACH ROW EXECUTE FUNCTION update_modified_column();




-- Insert root chapters (only numbers, because names go into localization table)
INSERT INTO chapters (chapter_number) VALUES 
(1), (2), (3), (4), (5), (6), (7), (8), (9), (10),
(11), (12), (13), (14), (15), (16), (17), (18), (19), (20), (21);

-- Insert English and Lithuanian chapter names
INSERT INTO chapter_descriptions (chapter_number, language_code, chapter_name) VALUES
(1, 'EN', 'LIVE ANIMALS; ANIMAL PRODUCTS'),
(2, 'EN', 'VEGETABLE PRODUCTS'),
(3, 'EN', 'ANIMAL, VEGETABLE OR MICROBIAL FATS AND OILS AND THEIR CLEAVAGE PRODUCTS; PREPARED EDIBLE FATS; ANIMAL OR VEGETABLE WAXES'),
(4, 'EN', 'PREPARED FOODSTUFFS; BEVERAGES, SPIRITS AND VINEGAR; TOBACCO AND MANUFACTURED TOBACCO SUBSTITUTES; PRODUCTS, WHETHER OR NOT CONTAINING NICOTINE, INTENDED FOR INHALATION WITHOUT COMBUSTION; OTHER NICOTINE CONTAINING PRODUCTS INTENDED FOR THE INTAKE OF NICOTINE INTO THE HUMAN BODY'),
(5, 'EN', 'MINERAL PRODUCTS'),
(6, 'EN', 'PRODUCTS OF THE CHEMICAL OR ALLIED INDUSTRIES'),
(7, 'EN', 'PLASTICS AND ARTICLES THEREOF; RUBBER AND ARTICLES THEREOF'),
(8, 'EN', 'RAW HIDES AND SKINS, LEATHER, FURSKINS AND ARTICLES THEREOF; SADDLERY AND HARNESS; TRAVEL GOODS, HANDBAGS AND SIMILAR CONTAINERS; ARTICLES OF ANIMAL GUT (OTHER THAN SILKWORM GUT)'),
(9, 'EN', 'WOOD AND ARTICLES OF WOOD; WOOD CHARCOAL; CORK AND ARTICLES OF CORK; MANUFACTURES OF STRAW, OF ESPARTO OR OF OTHER PLAITING MATERIALS; BASKETWARE AND WICKERWORK'),
(10, 'EN', 'PULP OF WOOD OR OF OTHER FIBROUS CELLULOSIC MATERIAL; RECOVERED (WASTE AND SCRAP) PAPER OR PAPERBOARD; PAPER AND PAPERBOARD AND ARTICLES THEREOF'),
(11, 'EN', 'TEXTILES AND TEXTILE ARTICLES'),
(12, 'EN', 'FOOTWEAR, HEADGEAR, UMBRELLAS, SUN UMBRELLAS, WALKING STICKS, SEAT-STICKS, WHIPS, RIDING-CROPS AND PARTS THEREOF; PREPARED FEATHERS AND ARTICLES MADE THEREWITH; ARTIFICIAL FLOWERS; ARTICLES OF HUMAN HAIR'),
(13, 'EN', 'ARTICLES OF STONE, PLASTER, CEMENT, ASBESTOS, MICA OR SIMILAR MATERIALS; CERAMIC PRODUCTS; GLASS AND GLASSWARE'),
(14, 'EN', 'NATURAL OR CULTURED PEARLS, PRECIOUS OR SEMI-PRECIOUS STONES, PRECIOUS METALS, METALS CLAD WITH PRECIOUS METAL, AND ARTICLES THEREOF; IMITATION JEWELLERY; COIN'),
(15, 'EN', 'BASE METALS AND ARTICLES OF BASE METAL'),
(16, 'EN', 'MACHINERY AND MECHANICAL APPLIANCES; ELECTRICAL EQUIPMENT; PARTS THEREOF; SOUND RECORDERS AND REPRODUCERS, TELEVISION IMAGE AND SOUND RECORDERS AND REPRODUCERS, AND PARTS AND ACCESSORIES OF SUCH ARTICLES'),
(17, 'EN', 'VEHICLES, AIRCRAFT, VESSELS AND ASSOCIATED TRANSPORT EQUIPMENT'),
(18, 'EN', 'OPTICAL, PHOTOGRAPHIC, CINEMATOGRAPHIC, MEASURING, CHECKING, PRECISION, MEDICAL OR SURGICAL INSTRUMENTS AND APPARATUS; CLOCKS AND WATCHES; MUSICAL INSTRUMENTS; PARTS AND ACCESSORIES THEREOF'),
(19, 'EN', 'ARMS AND AMMUNITION; PARTS AND ACCESSORIES THEREOF'),
(20, 'EN', 'MISCELLANEOUS MANUFACTURED ARTICLES'),
(21, 'EN', 'WORKS OF ART, COLLECTORS'' PIECES AND ANTIQUES'),

(1, 'LT', 'GYVI GYVŪNAI; GYVŪNINĖS KILMĖS PRODUKTAI'),
(2, 'LT', 'AUGALINIAI PRODUKTAI'),
(3, 'LT', 'GYVŪNINIAI, AUGALINIAI ARBA MIKROORGANIZMŲ RIEBALAI IR ALIEJUS BEI JŲ SKILIMO PRODUKTAI; PARUOŠTI VALGOMIEJI RIEBALAI; GYVŪNINIS ARBA AUGALINIS VAŠKAS'),
(4, 'LT', 'PREPARED FOODSTUFFS; BEVERAGES, SPIRITS AND VINEGAR; TOBACCO AND MANUFACTURED TOBACCO SUBSTITUTES; PRODUCTS, WHETHER OR NOT CONTAINING NICOTINE, INTENDED FOR INHALATION WITHOUT COMBUSTION; OTHER NICOTINE CONTAINING PRODUCTS INTENDED FOR THE INTAKE OF NICOTINE INTO THE HUMAN BODY'),
(5, 'LT', 'MINERALINIAI PRODUKTAI'),
(6, 'LT', 'CHEMIJOS PRAMONĖS IR JAI GIMININGŲ PRAMONĖS ŠAKŲ PRODUKCIJA'),
(7, 'LT', 'PLASTIKAI IR JŲ GAMINIAI; KAUČIUKAS IR JO GAMINIAI'),
(8, 'LT', 'ŽALIAVINĖS ODOS, IŠDIRBTA ODA, KAILIAI IR JŲ DIRBINIAI; BALNAI IR PAKINKTAI; KELIONĖS REIKMENYS, RANKINĖS IR PANAŠŪS DAIKTAI; DIRBINIAI IŠ GYVŪNŲ ŽARNŲ (IŠSKYRUS ŠILKAVERPIŲ ŽARNAS)'),
(9, 'LT', 'MEDIENA IR MEDIENOS GAMINIAI; MEDŽIO ANGLYS; KAMŠTIENA IR KAMŠTIENOS DIRBINIAI; DIRBINIAI IŠ ŠIAUDŲ, ESPARTO ARBA IŠ KITŲ PYNIMO MEDŽIAGŲ; PINTINĖS IR KITI PINTI DIRBINIAI'),
(10, 'LT', 'MEDIENOS ARBA KITŲ PLUOŠTINIŲ CELIULIOZINIŲ MEDŽIAGŲ PLAUŠIENA; PERDIRBTI SKIRTAS POPIERIUS ARBA KARTONAS (ATLIEKOS IR LIEKANOS); POPIERIUS IR KARTONAS BEI JŲ GAMINIAI'),
(11, 'LT', 'TEKSTILĖS MEDŽIAGOS IR TEKSTILĖS DIRBINIAI'),
(12, 'LT', 'AVALYNĖ, GALVOS APDANGALAI, SKĖČIAI, SKĖČIAI NUO SAULĖS, LAZDOS, LAZDOS-SĖDYNĖS, VYTINIAI, BOTAGAI IR JŲ DALYS; PARUOŠTOS NAUDOTI PLUNKSNOS IR JŲ DIRBINIAI; DIRBTINĖS GĖLĖS; DIRBINIAI IŠ ŽMONIŲ PLAUKŲ'),
(13, 'LT', 'DIRBINIAI IŠ AKMENS, GIPSO, CEMENTO, ASBESTO, ŽĖRUČIO ARBA PANAŠIŲ MEDŽIAGŲ; KERAMIKOS DIRBINIAI; STIKLAS IR STIKLO DIRBINIAI'),
(14, 'LT', 'GAMTINIAI ARBA DIRBTINIU BŪDU IŠAUGINTI PERLAI, BRANGAKMENIAI ARBA PUSBRANGIAI AKMENYS, TAURIEJI METALAI, METALAI, PLAKIRUOTI TAURIUOJU METALU, BEI JŲ DIRBINIAI; DIRBTINĖ BIŽUTERIJA; MONETOS'),
(15, 'LT', 'NETAURIEJI METALAI IR NETAURIŲJŲ METALŲ GAMINIAI'),
(16, 'LT', 'MAŠINOS IR MECHANINIAI ĮRENGINIAI; ELEKTROS ĮRANGA; JŲ DALYS; GARSO ĮRAŠYMO IR ATKŪRIMO APARATAI, TELEVIZIJOS VAIZDO IR GARSO ĮRAŠYMO IR ATKŪRIMO APARATAI, ŠIŲ GAMINIŲ DALYS BEI REIKMENYS'),
(17, 'LT', 'ANTŽEMINIO, ORO, VANDENS TRANSPORTO PRIEMONĖS IR PAGALBINĖ TRANSPORTO ĮRANGA'),
(18, 'LT', 'OPTIKOS, FOTOGRAFIJOS, KINEMATOGRAFIJOS, MATAVIMO, TIKRINIMO, TIKSLIEJI, MEDICINOS ARBA CHIRURGIJOS PRIETAISAI IR APARATAI; LAIKRODŽIAI; MUZIKOS INSTRUMENTAI; JŲ DALYS IR REIKMENYS'),
(19, 'LT', 'GINKLAI IR ŠAUDMENYS; JŲ DALYS IR REIKMENYS'),
(20, 'LT', 'ĮVAIRŪS PRAMONĖS DIRBINIAI'),
(21, 'LT', 'MENO KŪRINIAI, KOLEKCIONAVIMO OBJEKTAI IR ANTIKVARINIAI DAIKTAI');



